### ISSUE TITLE
Time display problem

### ISSUE THREAD

**Issue by TeruNya1551** [PunishedPineapple/WhatDidYouSay#1]
![图片](https://user-images.githubusercontent.com/44634682/170864828-9e8122e2-0da1-4ee5-abb2-3fb8abcb67c5.png)

Time is always shown as [8:00] in the message bar.

**Comment by PunishedPineapple** [comment]
It shows the wrong time for me too, and I didn't even notice; sorry.  Thank you for letting me know.  I'll look into it this week.

**Comment by PunishedPineapple** [comment]
This is fixed in version 1.0.0.1.  You can update through the in-game plugin installer.
