### ISSUE TITLE
Toggle option to disable in Island Sanctuary

### ISSUE THREAD

**Issue by TheGokki** [PunishedPineapple/WhatDidYouSay#3]
Would love an option to disable this mod's functions in Island Sanctuary because the minions express themselves very frequently, filling my chat up. Works great otherwise!

**Comment by PunishedPineapple** [comment]
Ya, I noticed that last night when I finally put some minions out haha.  I should probably add a user-configurable blacklist or maybe let people override the basic config by zone.  I'll have to think about the best way to do it.

In the interim, you can type `/saywhat` in chat, and untick the checkbox for "Allow repeated speech to print to log." and you'll only see the bubbles once per zone.  Island should count as an instance for this setting I believe.  I know that's not super ideal, but that'll be the best option for at least a few days.

**Comment by TheGokki** [comment]
> let people override the basic config by zone

What about a `/saywhat mutezone` to mute the current zone? and a `/saywhat mutereset` to clear the mute list?

**Comment by PunishedPineapple** [comment]
Version 1.0.1.0 (which is now in the plugin installer if you have testing plugins enabled) has config options to override specific zones.  It also has text command shortcuts for this that are `/saywhat ban` and `/saywhat unban` to just block and unblock the current zone.

If there aren't any issues with the testing version after a couple of days, I'll move it to stable.
